#!/bin/sh
#
# Setup aliases to start, debug or kill lina

alias lstart="/asa/scripts/lstart.sh"
alias ldebug="/asa/scripts/ldebug.sh"
alias lattach="/asa/scripts/lattach.sh"
alias lkill="/asa/scripts/lkill.sh"
alias lclean="/asa/scripts/lclean.sh"
alias ltrap="/asa/scripts/ltrap.sh"

echo "[bashrc] Done."